# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "12ad595b7060f8c4f69a26b37d661faf"
name = "save-for-later-wishlist"
handle = "save-for-later-wishlist"
application_url = "https://publicly-putting-connecting-floppy.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, unauthenticated_read_product_listings, read_products"

[auth]
redirect_urls = [
  "https://publicly-putting-connecting-floppy.trycloudflare.com/auth/callback",
  "https://publicly-putting-connecting-floppy.trycloudflare.com/auth/shopify/callback",
  "https://publicly-putting-connecting-floppy.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
